esphome:
  name: minikeyboard

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid_home
  password: !secret wifi_password_home

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Minikeyboard Fallback Hotspot"
    password: "AaPhSUarmMbi"

captive_portal:

binary_sensor:
  - platform: gpio
    id: miniKeyboardButton1
    name: Button 1
    pin: 
      number: 23
      inverted: true
      mode:
        input: true
        pulldown: true

    filters:
      - delayed_on: 25ms
      - delayed_off: 25ms
  - platform: gpio
    id: miniKeyboardButton2
    name: Button 2
    pin: 
      number: 22
      inverted: true
      mode:
        input: true
        pulldown: true

    filters:
      - delayed_on: 25ms
      - delayed_off: 25ms
  - platform: gpio
    id: miniKeyboardButton3
    name: Button 3
    pin: 
      number: 18
      inverted: true
      mode:
        input: true
        pulldown: true

    filters:
      - delayed_on: 25ms
      - delayed_off: 25ms