esphome:
  name: office1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid_home
  password: !secret wifi_password_home

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Office1 Fallback Hotspot"
    password: "k2z3oy7QRiQj"

captive_portal:

sensor:
  - platform: dht
    pin: 5
    model: DHT11
    temperature:
      name: "Temperatura da sala"
    humidity:
      name: "Umidade da sala"
    update_interval: 30s

binary_sensor:
  - platform: gpio
    pin: 
      number: 4
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 100ms
    name: "Botão Sala"
